CREATE TABLE RECORDS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(512) NOT NULL,
    TEXT VARCHAR NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    LAST_UPDATE TIMESTAMP NOT NULL DEFAULT NOW(),
    DELETED BOOL NOT NULL DEFAULT FALSE
)