CREATE TABLE RECORDS (
  ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE      VARCHAR(512) NOT NULL,
  TEXT       VARCHAR      NOT NULL,

/* ARTICLE, QUOTE */
  TYPE       VARCHAR(32)  NOT NULL,

  CREATED_ON TIMESTAMP    NOT NULL,
  UPDATED_ON TIMESTAMP    NOT NULL
);

CREATE TABLE TAGS (
  ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME   VARCHAR_IGNORECASE(64) NOT NULL UNIQUE,
  USAGES INT                    NOT NULL DEFAULT 0
);

CREATE TABLE RECORDS_TAGS (
  RECORD_ID BIGINT NOT NULL,
  TAG_ID    BIGINT NOT NULL
);