CREATE TABLE RECORDS (
  ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE       VARCHAR(512) NOT NULL,
  TEXT        VARCHAR      NOT NULL,
/* ARTICLE, QUOTE */
  TYPE        VARCHAR(32)  NOT NULL,
  CREATED     TIMESTAMP    NOT NULL,
  LAST_UPDATE TIMESTAMP    NOT NULL
);

CREATE TABLE TAGS (
  ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR_IGNORECASE(64) NOT NULL
);

CREATE TABLE RECORDS_TAGS (
  RECORD_ID BIGINT NOT NULL,
  TAG_ID    BIGINT NOT NULL
);